import os
import resend
from typing import List
from datetime import datetime


def send_meeting_prep_email(
    recipients: List[str],
    subject: str,
    html_content: str,
    from_name: str = "ET-Labs Meeting Prep"
) -> dict:
    api_key = os.environ.get("RESEND_API_KEY")
    from_email = os.environ.get("RESEND_FROM_EMAIL", "onboarding@resend.dev")

    if not api_key:
        return {
            "success": False,
            "error": "RESEND_API_KEY not configured. Please add your Resend API key to send emails."
        }

    if not recipients:
        return {
            "success": False,
            "error": "No recipients specified"
        }

    try:
        resend.api_key = api_key

        params = {
            "from": f"{from_name} <{from_email}>",
            "to": recipients,
            "subject": subject,
            "html": html_content
        }

        email_response = resend.Emails.send(params)

        try:
            from cost_tracker import log_cost_event
            log_cost_event(
                event_type="email_send",
                agent_name="Meeting Prep Agent",
                metadata={"recipients": recipients, "subject": subject}
            )
        except Exception:
            pass

        return {
            "success": True,
            "message": f"Email sent successfully to {', '.join(recipients)}",
            "email_id": email_response.get("id") if isinstance(email_response, dict) else str(email_response)
        }

    except Exception as e:
        return {
            "success": False,
            "error": f"Failed to send email: {str(e)}"
        }


def format_meeting_prep_as_html(
    person_label: str,
    company: str,
    topic: str,
    report_html: str
) -> str:
    html = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body style="font-family: Arial, sans-serif; line-height: 1.6; color: #374151; max-width: 800px; margin: 0 auto; padding: 20px;">
        <div style="background: linear-gradient(135deg, #1a4731 0%, #2d6a4f 100%); padding: 30px; border-radius: 12px 12px 0 0;">
            <h1 style="color: white; margin: 0; font-size: 24px;">Meeting Preparation Brief</h1>
            <p style="color: rgba(255,255,255,0.9); margin: 10px 0 0 0; font-size: 16px;">Meeting with {person_label} at {company}</p>
            <p style="color: rgba(255,255,255,0.8); margin: 5px 0 0 0; font-size: 14px;">Topic: {topic}</p>
            <p style="color: rgba(255,255,255,0.7); margin: 5px 0 0 0; font-size: 12px;">Generated on {datetime.now().strftime('%B %d, %Y at %I:%M %p')}</p>
        </div>

        <div style="background: white; padding: 25px; border: 1px solid #e5e7eb; border-top: none;">
            {report_html}
        </div>

        <div style="text-align: center; padding: 20px; color: #9ca3af; font-size: 12px; background: #f9fafb; border: 1px solid #e5e7eb; border-top: none; border-radius: 0 0 12px 12px;">
            <p>This meeting brief was generated by ET-Labs AI Agent Marketplace</p>
            <p style="margin: 5px 0 0 0;">&copy; 2026 ET-Labs. All rights reserved.</p>
        </div>
    </body>
    </html>
    """
    return html
